# Summary.cmake - Build Configuration Summary Module

message(STATUS "")
message(STATUS "╔════════════════════════════════════════════════════════════════════╗")
message(STATUS "║              RhodoEngine Build Configuration                       ║")
message(STATUS "╚════════════════════════════════════════════════════════════════════╝")
message(STATUS "")
message(STATUS "  Build Configuration:")
message(STATUS "    Build Type:          ${CMAKE_BUILD_TYPE}")
message(STATUS "    Platform:            ${RH_PLATFORM}")
message(STATUS "    C++ Standard:        C++${CMAKE_CXX_STANDARD}")
message(STATUS "    C++ Modules:         ENABLED")
message(STATUS "    Assertions:          ${RH_ENABLE_ASSERTS}")
message(STATUS "")
message(STATUS "  Code Quality Tools:")
message(STATUS "    Clang-Format:        ${RH_ENABLE_CLANG_FORMAT}")
if (RH_ENABLE_CLANG_FORMAT)
    message(STATUS "                         ${CLANG_FORMAT_EXE}")
endif ()
message(STATUS "    Clang-Tidy:          ${RH_ENABLE_CLANG_TIDY}")
if (RH_ENABLE_CLANG_TIDY)
    message(STATUS "                         ${CLANG_TIDY_EXE}")
endif ()
message(STATUS "")
message(STATUS "  Build Options:")
message(STATUS "    Build Tests:         ${RH_BUILD_TESTS}")
message(STATUS "")

# Quick start guide
message(STATUS "  Quick Start:")
message(STATUS "    Configure:           cmake -B build")
message(STATUS "    Build:               cmake --build build")
if (RH_BUILD_TESTS)
    message(STATUS "    Test:                ctest --test-dir build")
endif ()
if (RH_ENABLE_CLANG_FORMAT)
    message(STATUS "    Format Code:         cmake --build build --target format")
endif ()
if (RH_ENABLE_CLANG_TIDY)
    message(STATUS "    Run Linter:          cmake --build build --target tidy")
endif ()
message(STATUS "")
message(STATUS "╚════════════════════════════════════════════════════════════════════╝")
message(STATUS "")
